name: Integration Tests (charm-ci)

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  integration-test:
    uses: canonical/charm-ci/.github/workflows/integration-test.yml@main
    secrets: inherit
    with:
      working-directory: .
