name: Publish (charm-ci)

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    permissions:
      actions: read
      contents: write
    with:
      channel: latest/edge
      integration-workflow-name: integration-test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}

  release-libs:
    name: Release charm libs
    needs: publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: canonical/charming-actions/release-libraries@2.7.0
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
