name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@v0.0.1-alpha.1
    permissions:
      actions: read
      contents: write
    with:
      channel: latest/edge
      integration-workflow-name: integration-test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}

  release-libs:
    name: Release any bumped charm library
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v6
        with:
          path: charm
      - name: Release libraries
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMHUB_TOKEN }}"
          CHARM_PATH: '.'
          CHARM_NAME: 'traefik-k8s'
        run: |
          sudo snap install charmcraft --classic
          cd "${GITHUB_WORKSPACE}/charm/${CHARM_PATH}"
          # Get the charm name
          if [[ $CHARM_NAME = "" ]]; then echo "Error: empty charm name." && exit 1; fi
          charmlib_path="${CHARM_NAME//-/_}"
          # For each library belonging to the charm, publish it
          if [ -d "lib/charms/${charmlib_path}" ]; then
            for lib in $(find "lib/charms/${charmlib_path}" -type f | sed 's|lib/||' | sed 's/.py$//' | sed 's|/|.|g'); do
              charmcraft publish-lib "$lib"
            done
          fi
