name: Release Charm

on:
  push:
    branches:
      - main
      - track/**

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@v2
    secrets: inherit
