name: Tests

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Test
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      with-uv: true
